package tcc.acs_cadastro_mobile;

public class Constants {

    public enum Citizen {
        DESCRIPTION, ANOTHER, DONT_KNOWN,

        //StreetSituationModel.class
        STREET_SITUATION, STREET, BENEFIT, FAMILY,
        HYGIENE, BATH, SANITARY, ORAL,
        FAMILY_VISIT,
        ANOTHER_INSTITUTION,
        FEEDING, FOOD_PER_DAY, RESTAURANT, RESTAURANT_DONATION, RELIGIOUS_GROUP, POPULAR,

        //HealthConditionsModel.class
        HEALTH_CONDITIONS, WEIGHT,
        PLANT,
        INTERMENT,
        RESPIRATORY_DISEASE, ASTHMA, EMPHYSEMA,
        KIDNEY_DISEASE, INSUFFICIENCY,
        HEART_DISEASE,
        DISEASES, SMOKER, HYPERTENSION, ALCOHOL, DRUGS, DIABETES, AVC, HEART_ATTACK, LEPROSY, TUBERCULOSIS,
        CANCER, IN_BED, DOMICILED, OTHER_PRACTICES, MENTAL_HEALTH,
        PREGNANT,

        //SocialDemographicModel.class
        TB_DEFICIENCY, DEFICIENCY, HEARING, VISUAL, INTELLECTUAL, PHYSICAL,
        SEXUAL_ORIENTATION1, SEXUAL_ORIENTATION,
        COMMUNITY_TRADITIONAL1, COMMUNITY_TRADITIONAL,
        HEALTH_GROUP, CAREGIVER, COMMUNITY_GROUP, HEALTH_PLAN,
        EDUCATION_EMPLOYMENT, SCHOOL, OCCUPATION, EDUCATION, EMPLOYMENT,
        SOCIAL_DEMOGRAPHIC, KINSHIP, KIDS_09,

        //PersonalDataModel.class
        CONTACT, PHONE, EMAIL,
        TB_NATIONALITY, NATIONALITY, NATION_BIRTH, UF, CITY,
        GENDER_RACE, GENDER, RACE,
        TB_RESPONSIBLE, RESPONSIBLE, NUM_SUS, BIRTH_DATE,
        MOTHER, KNOWN, NAME,
        PARTICULAR, NUM_NIS, SOCIAL_NAME,
        PERSONAL_DATA
    }

    public enum Accompany {

        //RecordDataModel.class
        RECORD_DATA,
        RECORD_DETAILS, RECORD, PLACE_CARE, TYPE_CARE, SHIFT,
        ANTHROPOMETRIC, WEIGHT, HEIGHT, VACCINATES,
        KID_PREGNANT, BREAST_FEEDING, DUM, PLANNED_PREGNANCY, WEEKS, PREVIOUS, CHILD_BIRTH, HOME_CARE,

        //ConditionsModel.class
        CONDITIONS,
        CONDITIONS_DISEASES, ASTHMA, MALNUTRITION, DIABETES, DPOC, HYPERTENSION, OBESITY, PRENATAL, CHILD_CARE,
        PUERPERIUM, SEXUAL_HEALTH, SMOKING, ALCOHOL, DRUGS, MENTAL_HEALTH, REHABILITATION,
        COMMUNICABLE_DISEASES, TUBERCULOSIS, LEPROSY, DENGUE, DST,
        TRACKING_DISEASES, CERVICAL_CANCER, BREAST_CANCER, CARDIOVASCULAR,

        //ExamsModel.class
        EXAMS, PIC,
        REQUEST_EXAMS, EVALUATED_EXAMS,
        TOTAL_CHOLESTEROL, CREATINE, EAS_EQU, ELECTROCARDIOGRAM, HEMOGLOBIN,
        SPIROMETRY, SPUTUM, GLYCEMIA, HDL, GLYCEMIC_HEMOGLIBIN, BLOOD_COUNT, LDL, EYES, SYPHILIS,
        HIV, HUMAN_ANTIGLOBULIN, EAR_TEST, PREGNANCY_TEST, EYE_TEST, FOOT_TEST,  ULTRASONOGRAPHY, UROCULTURE,

        //NasfConductModel.class
        NASF_CONDUCT,
        NASF, EVALUATION, PROCEDURES, PRESCRIPTION,
        CONDUCT, SCHEDULE_APPOINTMENT, SCHEDULE_CARE, GROUPS_SCHEDULE, NASF_SCHEDULE, RELEASES,
        FORWARDING, IN_DAY, SPECIALIZED_SERVICE, CAPS, HOSPITALIZATION,HOME_CARE_SERVICE , URGENCY, INTER_SECTORAL;
    }


    public enum Visit{
        //RecordVisitModel.class
        RECORD_DETAILS, RECORD, SHIFT, NUM_SUS,
        RECORD_VISIT, IS_SHARED,

        //ReasonsVisitModel.class
        REASONS_VISIT, RESULT,
        ACTIVE_SEARCH, APPOINTMENT, EXAM, VACCINE, CONDITIONS,
        
        FOLLOWING, PREGNANT, PUERPERA, NEW_BORN, CHILD, MALNUTRITION, REHABILITATION, HYPERTENSION,
        DIABETES, ASTHMA, COPD_EMPHYSEMA, CANCER, CHRONIC_DISEASE, LEPROSY, TUBERCULOSIS,
        RESPIRATORY, SMOKER, HOME_BEDDING, VULNERABILITY, BOLSA_FAMILIA, MENTAL_HEALTH, ALCOHOL, DRUGS,

        ANOTHER_REASONS, RECORD_UPDATE, PERIODIC_VISIT, INTERMENT, CONTROL_ENVIRONMENTS,
        COLLECTIVE_ACTIVITIES, GUIDANCE, OTHERS;
    }

    public enum Residence{
        //AddressDataModel.class
        ADDRESS_DATA,
        STREET_LOCATION, TYPE, NAME, NUMBER, COMPLEMENT,
        CITY_LOCATION, NEIGHBORHOOD, UF, CITY, CEP,
        PHONES, HOME, REFERENCE,

        //HousingConditionsModel.class
        HOUSING_CONDITIONS, ELECTRICITY,
        HOUSING_SITUATION, SITUATION, LOCATION, OWNERSHIP,
        HOUSE, RESIDENTS, ROOMS, ACCESS, CONSTRUCTION, CONSTRUCTION_TYPE,
        WATER_SANITATION, WATER_SUPPLY, WATER_TREATMENT, BATHROOM,
        PET, HAS_PET, CAT, DOG, BIRD, CREATION, ANOTHER, PETS;
    }
}